name:               "A Curious Animal"
description:        "Born to be curious, born to be animal !!!"
meta_description:   "technology, gis, javascript, web, mapping, openlayers, leaflet, jquery, acuriousanimal, acanimal"
author:             "acanimal"
author_description: "Computer Science, passionate programmer and an eternal rookie guitar player."
url:                "http://acuriousanimal.com"
baseurl:            "/"

markdown:           kramdown

highlighter:        rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

logo:               true
paginate:           10
google_analytics:   'UA-8297669-2'
disqus_shortname:   'acuriousanimal'

gems:
  - jekyll-paginate
  - jekyll-sitemap
